### ISSUE TITLE
ensembl.tsv

### ISSUE THREAD

**Issue by suke18** [bryanhe/ST-Net#7]
Hello Bryan, 

I recently read your work stnet and am very interested in the model. I tried your command "python3 -m stnet prepare spatial" but there is no ensembl.pkl or ensembl.tsv files in the utils folder. 

Thanks,
Kenong

**Comment by suke18** [comment]
solved

**Comment by yongshuo-Z** [comment]
@suke18 Hi, I met the same issue. Would you mind sharing the solution?

**Comment by suke18** [comment]
#2 I think this thread might answer your question. I downloaded it from https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=md_ensembl_id&status=Approved&status=Entry%20Withdrawn&hgnc_dbtag=on&order_by=gd_app_sym_sort&format=text&submit=submit. I forget where to download the .pkl but it is on my laptop for some reason.

**Comment by yongshuo-Z** [comment]
> #2 I think this thread might answer your question. I downloaded it from https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=md_ensembl_id&status=Approved&status=Entry%20Withdrawn&hgnc_dbtag=on&order_by=gd_app_sym_sort&format=text&submit=submit. I forget where to download the .pkl but it is on my laptop for some reason.

Thanks a lot! Solved the .tsv. Could you share the .pkl if possible?

**Comment by johnchen99** [comment]
> > #2 I think this thread might answer your question. I downloaded it from https://www.genenames.org/cgi-bin/download/custom?col=gd_hgnc_id&col=gd_app_sym&col=gd_app_name&col=md_ensembl_id&status=Approved&status=Entry%20Withdrawn&hgnc_dbtag=on&order_by=gd_app_sym_sort&format=text&submit=submit. I forget where to download the .pkl but it is on my laptop for some reason.
> 
> Thanks a lot! Solved the .tsv. Could you share the .pkl if possible?

Hi, may I know if you've a solution for ensembl.pkl?
